kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: movie-catalog-service-role-binding
  namespace: ${NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: movie-catalog-service-service-account
    namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: movie-catalog-service-role
  apiGroup: rbac.authorization.k8s.io