kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: movie-catalog-service-role-binding
  namespace: ${NAMESPACE}
  annotations:
    author: DhiegoDuarte
    email: dhiegoduarte@gmail.com
    company: ClaroBR
  labels:
    application: movie-catalog-service
    revision: TODO_COMO_COLOCAR_O_COMMIT_AQUI #4c511f16ef2644854d04cabebfcecc82be0eb04f
    env: stage
    version: "1.0.0"
    owner: movies-squad
subjects:
  - kind: ServiceAccount
    name: movie-catalog-service-service-account
    namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: movie-catalog-service-role
  apiGroup: rbac.authorization.k8s.io