kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ${NAMESPACE}
  name: movie-catalog-service-role
  annotations:
    author: DhiegoDuarte
    email: dhiegoduarte@gmail.com
    company: ClaroBR
  labels:
    application: movie-catalog-service
    revision: TODO_COMO_COLOCAR_O_COMMIT_AQUI #4c511f16ef2644854d04cabebfcecc82be0eb04f
    env: stage
    version: "1.0.0"
    owner: movies-squad
rules: # necessario para que o MS utilize a lib Spring Cloud Kubernetes
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","configmaps"]
  verbs: ["get", "list", "watch"]