kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ${NAMESPACE}
  name: movie-catalog-service-sidecar-fatura-role  
rules: # necessario para que o MS utilize a lib Spring Cloud Kubernetes
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","configmaps","secrets"]
  verbs: ["get", "list", "watch"]